"""
generate_multi_agent_rollouts_vllm.py
====================

Rollout generation ONLY — multi-agent limitation extraction (3-HOP + 4-MODE),
generated by a LOCAL **Qwen3-4B** served through a vLLM OpenAI-compatible server.

This is a drop-in replacement for `rollout_gpt.py`:
  * autogen + GPT-4o-mini  ->  plain `openai` client pointed at vLLM
  * tiktoken               ->  the model's own HF tokenizer (exact budgeting)
  * sequential workers     ->  ThreadPoolExecutor (vLLM batches the requests)
  * Qwen3 thinking mode DISABLED (`enable_thinking=false`) so outputs are the
    clean bullet lists the stepwise scorer parses and you train on.

It computes NO rewards. Scoring stays with `select_data_stepwise_process_reward.py`
(GPT-4o-mini reward/judge), which reads `rollout_data_full.json`.

The output JSON schema is byte-for-byte compatible with the old script:
  - rollout_data_full.json     (feed this to the stepwise scorer)
  - rollout_data_worker.json / _leader.json / _master.json

Per paper we run N rollouts (default 4), each bound 1:1 to an EXPLORATION MODE
and a sampling config:

    rollout 0  ->  strict_grounding   (T=0.7, seed=42)
    rollout 1  ->  critique_heavy     (T=0.9, seed=123)
    rollout 2  ->  retrieval_heavy    (T=1.1, seed=456)
    rollout 3  ->  search_repair      (T=0.5, seed=789)

Within every rollout, each of the 6 specialist workers runs a 3-HOP chain:
    HOP 1 SEARCH -> HOP 2 QUERY -> HOP 3 DRAFT

Everything is env-overridable so the PBS script can drive it.

Run (server must already be up):
    VLLM_BASE_URL=http://127.0.0.1:8000/v1 SERVED_MODEL_NAME=student \
    python generate_multi_agent_rollouts_vllm.py
"""

import os
import re
import ast
import json
import time
import random
import threading
from concurrent.futures import ThreadPoolExecutor

import pandas as pd
from tqdm import tqdm
from openai import OpenAI

# ==========================================
# 1. CONFIG  (all env-overridable)
# ==========================================



# =============================================================================
# ENVIRONMENT CONFIGURATION
# All input/output locations are supplied at run time. No paths, dataset sizes
# or credentials are stored in this file.
# =============================================================================
def _require_env(name, hint=""):
    """Return a mandatory environment variable, or exit with a clear message."""
    value = os.environ.get(name)
    if not value:
        raise SystemExit(
            f"Required environment variable {name} is not set."
            + (f"  Expected: {hint}" if hint else "")
        )
    return value


def _optional_int(name):
    """Return an int env var, or None when unset/blank (meaning 'no limit')."""
    raw = os.environ.get(name, "").strip()
    if raw in ("", "none", "None", "null"):
        return None
    return int(raw)


MODEL_PATH = _require_env("MODEL_PATH", "student checkpoint directory (Qwen3-4B class)")
VLLM_BASE_URL = os.environ.get("VLLM_BASE_URL", "http://127.0.0.1:8000/v1")
VLLM_API_KEY  = os.environ.get("VLLM_API_KEY", "EMPTY")

# Which served model / LoRA adapter each role should hit. With a plain base-model
# server all three are the same served name. Once you have adapters, start vLLM
# with --lora-modules worker=... leader=... master=... and set:
#   WORKER_MODEL=worker LEADER_MODEL=leader MASTER_MODEL=master
SERVED_MODEL_NAME = os.environ.get("SERVED_MODEL_NAME", "student")
WORKER_MODEL = os.environ.get("WORKER_MODEL", SERVED_MODEL_NAME)
LEADER_MODEL = os.environ.get("LEADER_MODEL", SERVED_MODEL_NAME)
MASTER_MODEL = os.environ.get("MASTER_MODEL", SERVED_MODEL_NAME)

ENABLE_THINKING = os.environ.get("ENABLE_THINKING", "0") == "1"

INPUT_CSV = _require_env("INPUT_CSV", "source CSV of papers")
OUTPUT_DIR = _require_env("OUTPUT_DIR", "directory to write rollout JSON into")
CHECKPOINT_DIR = os.path.join(OUTPUT_DIR, "checkpoints_per_paper")
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

OUTPUT_FULL_JSON   = os.path.join(OUTPUT_DIR, "rollout_data_full.json")
OUTPUT_WORKER_JSON = os.path.join(OUTPUT_DIR, "rollout_data_worker.json")
OUTPUT_LEADER_JSON = os.path.join(OUTPUT_DIR, "rollout_data_leader.json")
OUTPUT_MASTER_JSON = os.path.join(OUTPUT_DIR, "rollout_data_master.json")

INPUT_COL    = os.environ.get("INPUT_COL", "input_text_cleaned")
GT_COL       = os.environ.get("GT_COL", "ground_truth_lim_peer")
CITATION_COL = os.environ.get("CITATION_COL", "ret_abs_int_cit")

# Context budget. vLLM is started with --max-model-len 16384, so the paper text
# must leave room for hop instructions + generation. 8k is the sweet spot.
PAPER_TOKEN_LIMIT    = int(os.environ.get("PAPER_TOKEN_LIMIT", 8000))
CITATION_TOKEN_LIMIT = int(os.environ.get("CITATION_TOKEN_LIMIT", 4000))
MAX_MODEL_LEN        = int(os.environ.get("MAX_MODEL_LEN", 16384))

# Row slice of the CSV. Keep the held-out evaluation slice out of this range.
# Optional slice of the input file. Both unset => process the whole file.
ROW_START = _optional_int("ROW_START") or 0
ROW_END   = _optional_int("ROW_END")

N_ROLLOUTS       = int(os.environ.get("N_ROLLOUTS", 4))
N_WORKER_THREADS = int(os.environ.get("N_WORKER_THREADS", 6))
REQUEST_TIMEOUT  = int(os.environ.get("REQUEST_TIMEOUT", 900))
MAX_RETRIES      = int(os.environ.get("MAX_RETRIES", 4))

APPLY_MASTER_TOT = os.environ.get("APPLY_MASTER_TOT", "1") == "1"

ROLLOUT_CONFIGS = [
    {"rollout_id": 0, "temperature": 0.7, "top_p": 0.90, "seed": 42,  "mode": "strict_grounding"},
    {"rollout_id": 1, "temperature": 0.9, "top_p": 0.95, "seed": 123, "mode": "critique_heavy"},
    {"rollout_id": 2, "temperature": 1.1, "top_p": 1.00, "seed": 456, "mode": "retrieval_heavy"},
    {"rollout_id": 3, "temperature": 0.5, "top_p": 0.85, "seed": 789, "mode": "search_repair"},
][:N_ROLLOUTS]

# Leader & Master are NOT bound to worker exploration modes; they get their own
# sampling configs indexed by rollout position.
LEADER_CONFIGS = [
    {"temperature": 0.4, "top_p": 0.90, "seed": 11},
    {"temperature": 0.5, "top_p": 0.95, "seed": 22},
    {"temperature": 0.4, "top_p": 0.90, "seed": 33},
    {"temperature": 0.6, "top_p": 0.95, "seed": 44},
]
MASTER_CONFIGS = [
    {"temperature": 0.5, "top_p": 0.90, "seed": 101},
    {"temperature": 0.6, "top_p": 0.95, "seed": 202},
    {"temperature": 0.4, "top_p": 0.90, "seed": 303},
    {"temperature": 0.7, "top_p": 0.95, "seed": 404},
]

# ==========================================
# 1b. MODE DEFINITIONS (action config + prompt fragment)
# ==========================================

MODE_PROMPT_FRAGMENTS = {
    "strict_grounding": (
        "STRICT GROUNDING MODE. Be conservative: prefer fewer limitation units, "
        "each with a DIRECT evidence anchor. You MUST cite evidence IDs like [E12] "
        "that appear in the paper text for every limitation. Ask-when-Needed is ON: "
        "if the paper does not contain enough evidence to support a limitation, OMIT "
        "it or explicitly note the missing evidence rather than speculating. There is "
        "no external critique loop, so every claim must stand on its own."
    ),
    "critique_heavy": (
        "CRITIQUE-HEAVY MODE (MultiCritique + SAND). Search harder for high-impact "
        "limitations, but keep every claim tied to evidence. A reviewer/leader agent "
        "will critique your output over multiple rounds; anticipate that scrutiny and "
        "make each point defensible, specific, and non-generic."
    ),
    "retrieval_heavy": (
        "RETRIEVAL-HEAVY MODE (MemInsight / RAG). Use the provided cited / retrieved "
        "context aggressively (expanded top-k, knowledge-graph links, re-ranked by "
        "relevance) to test novelty, baselines, and unsupported claims against the "
        "prior literature. When a limitation is grounded in a retrieved paper, cite it "
        "as (Ref: PaperN)."
    ),
    "search_repair": (
        "SEARCH/REPAIR MODE (Tree-of-Thought + self-repair). Explore multiple "
        "reasoning paths internally, then self-critique and repair weak points before "
        "committing. Produce precise, evidence-backed, nonredundant statements."
    ),
}

MODE_ACTION_CONFIG = {
    "strict_grounding": {
        "cite_evidence_ids": True, "ask_when_needed": True, "critique_rounds": 0,
        "use_retrieval": False, "retrieval_top_k": 0, "include_kg": False,
        "reranking": False, "tot_at_master": False,
    },
    "critique_heavy": {
        "cite_evidence_ids": True, "ask_when_needed": False, "critique_rounds": 2,
        "use_retrieval": False, "retrieval_top_k": 0, "include_kg": False,
        "reranking": False, "tot_at_master": False,
    },
    "retrieval_heavy": {
        "cite_evidence_ids": False, "ask_when_needed": False, "critique_rounds": 1,
        "use_retrieval": True, "retrieval_top_k": 8, "include_kg": True,
        "reranking": True, "tot_at_master": False,
    },
    "search_repair": {
        "cite_evidence_ids": True, "ask_when_needed": False, "critique_rounds": 1,
        "use_retrieval": False, "retrieval_top_k": 0, "include_kg": False,
        "reranking": False, "tot_at_master": True,
    },
}

# ==========================================
# 2. WORKER PROMPTS  (UNCHANGED from rollout_gpt.py)
# ==========================================

def get_novelty_significance_prompt(paper_content):
    return f"""You are a highly skeptical expert focused on limitations related to novelty and significance. Scrutinize whether contributions are truly novel or merely incremental, whether claims of importance are overstated, whether the problem addressed is impactful, and whether motivations or real-world relevance are weakly justified.
Look for: rebranding existing ideas without substantial improvement, lack of clear differentiation from prior work, exaggerated claims of breakthrough, narrow scope that limits broader significance, or failure to articulate why the work matters.
Provide a concise bullet list of novelty- and significance-related limitations with explanations and evidence from the paper.
PAPER CONTENT:
{paper_content}"""

def get_theoretical_methodological_prompt(paper_content):
    return f"""You are an expert in theoretical and methodological soundness, including ablations and component analysis. Scrutinize the core method, theoretical claims, and component breakdowns for flaws: unrealistic assumptions, missing proofs, logical gaps, oversimplifications, incomplete dissections of components, missing ablations, or ablations that do not convincingly attribute performance gains.
Provide a bullet list of theoretical, methodological, and ablation-related limitations with supporting evidence.
PAPER CONTENT:
{paper_content}"""

def get_experimental_evaluation_prompt(paper_content):
    return f"""You specialize in experimental evaluation: validation, rigor, comparisons, baselines, and metrics. Find weaknesses: insufficient runs, lack of statistical significance, cherry-picked results, narrow conditions, inappropriate or outdated baselines, incomplete comparisons, misleading metrics, missing error bars, or overemphasis on minor gains.
Provide a bullet list of experimental evaluation-related limitations.
PAPER CONTENT:
{paper_content}"""

def get_generalization_robustness_efficiency_prompt(paper_content):
    return f"""Your expertise covers generalization, robustness, computational efficiency, and real-world applicability. Evaluate whether the method performs well beyond tested settings, is practical in terms of resources, and addresses genuine deployment needs.
Point out: overfitting to benchmarks, lack of out-of-distribution testing, sensitivity to hyperparameters, excessive training/inference demands, reliance on synthetic data, ignoring cost/latency constraints, or lack of user studies.
Provide a bullet list of generalization-, robustness-, efficiency-, and applicability-related limitations.
PAPER CONTENT:
{paper_content}"""

def get_clarity_interpretability_reproducibility_prompt(paper_content):
    return f"""You focus on clarity, interpretability, and reproducibility. Scrutinize for: unclear explanations, lack of explainability or insights into decisions, and insufficient details for replication (code, data, hyperparameters, protocols, seeds).
Provide a bullet list of clarity-, interpretability-, and reproducibility-related limitations, with suggestions where relevant.
PAPER CONTENT:
{paper_content}"""

def get_data_ethics_prompt(paper_content):
    return f"""You specialize in data integrity, bias, fairness, and ethical considerations. Scrutinize datasets for: collection, labeling, cleaning, representativeness, or documentation issues; and the overall work for biases, fairness problems, privacy risks, dual-use concerns, or societal impacts.
Provide a bullet list of data integrity-, bias-, fairness-, and ethics-related limitations.
PAPER CONTENT:
{paper_content}"""

WORKER_CONFIGS = [
    ("Novelty_Significance_Agent",                     get_novelty_significance_prompt,                      "novelty and significance"),
    ("Theoretical_Methodological_Agent",               get_theoretical_methodological_prompt,                "theoretical and methodological soundness (including ablations)"),
    ("Experimental_Evaluation_Agent",                  get_experimental_evaluation_prompt,                   "experimental evaluation, baselines, and metrics"),
    ("Generalization_Robustness_Efficiency_Agent",     get_generalization_robustness_efficiency_prompt,      "generalization, robustness, efficiency, and applicability"),
    ("Clarity_Interpretability_Reproducibility_Agent", get_clarity_interpretability_reproducibility_prompt,  "clarity, interpretability, and reproducibility"),
    ("Data_Ethics_Agent",                              get_data_ethics_prompt,                               "data integrity, bias, fairness, and ethics"),
]

# ==========================================
# 3. LEADER / MASTER PROMPTS  (UNCHANGED)
# ==========================================

def get_leader_system_prompt():
    return """You are the Leader Agent coordinating a team of 6 specialist agents to identify limitations in a scientific paper.

Your job has TWO modes:

MODE A — Providing FEEDBACK to a worker:
When a worker has just submitted their initial bullet list of limitations, give targeted feedback in ONE message:
- Identify vague statements and demand specificity.
- Flag limitations that lack evidence from the paper.
- Point out missing angles in the worker's specialty area.
- If a limitation is generic (could apply to any paper), say so.
- Be strict but constructive. Keep feedback focused — 3 to 6 concrete points.
- End with: "Please revise and send your updated bullet list."

MODE B — Handing off to the Master Agent:
Once you have collected revised outputs from all 6 workers, summarize and forward them. Format:
"Master Agent, here are the limitation analyses from the team:
[Worker name]: [bullet list]
[Worker name]: [bullet list]
...
Please synthesize them into a single, consolidated, non-redundant, high-quality list of limitations, grouped by category."

Do NOT generate limitations yourself. Only orchestrate, critique, and forward."""

def get_master_system_prompt():
    return """You are the Master Agent. You receive limitation analyses from 6 specialist workers (via the Leader Agent) and produce ONE final consolidated list.

TASK:
- Integrate all specialist outputs.
- Remove redundancies (merge similar limitations).
- Prioritize the most severe and well-justified ones.
- Preserve specificity and evidence from the originals.
- Organize by category (Novelty & Significance, Theoretical, Experimental, Generalization, Clarity, Data & Ethics).
- Do NOT introduce new limitations not raised by specialists.
- Aim for 10-20 strong limitations.

OUTPUT FORMAT:
Start with: "Here is the consolidated list of key limitations identified in the paper:"
Then a bulleted list:
- **Category:** Specific limitation (with brief explanation and evidence)."""

# ==========================================
# 3b. HOP INSTRUCTIONS
# ==========================================

HOP_USER_INSTRUCTIONS = {
    "search": (
        "HOP 1 — SEARCH. Cast a wide net over the paper (and any provided retrieved "
        "context). List every plausible CANDIDATE limitation in your specialty. For "
        "each candidate attach a concrete evidence anchor. Prioritize recall; you will "
        "filter later. Output a raw candidate list."
    ),
    "query": (
        "HOP 2 — QUERY. Below are your SEARCH candidates. Interrogate each against the "
        "paper's actual evidence: CONFIRM or REJECT, state the direct evidence anchor, "
        "and drop anything speculative, redundant, or unsupported. Keep only the "
        "limitation units that survive scrutiny.\n\n=== SEARCH CANDIDATES ===\n{search_out}"
    ),
    "draft": (
        "HOP 3 — DRAFT. Using the VERIFIED units below, write the final bullet list for "
        "your specialty. Each bullet must be precise, evidence-backed, nonredundant, and "
        "phrased to withstand a verifier's criticism. Follow the OUTPUT FORMAT in your "
        "system instructions.\n\n=== VERIFIED UNITS (from QUERY hop) ===\n{query_out}"
    ),
}

def build_agent_system(base_sys, mode, hop, action, retrieval_context=""):
    """Wrap a base agent system prompt with mode fragment + hop marker + mode knobs."""
    frag = MODE_PROMPT_FRAGMENTS[mode]
    extras = []
    if action.get("cite_evidence_ids"):
        extras.append("You MUST cite evidence IDs like [E12] (present in the paper text) for every limitation.")
    if action.get("ask_when_needed"):
        extras.append("Ask-when-Needed: if evidence is insufficient, omit the point or flag the missing evidence rather than speculating.")
    if action.get("use_retrieval"):
        knobs = [f"top_k={action.get('retrieval_top_k')}"]
        if action.get("include_kg"):
            knobs.append("knowledge-graph links included")
        if action.get("reranking"):
            knobs.append("relevance re-ranking enabled")
        extras.append("Retrieval settings: " + ", ".join(knobs) + ". Use the retrieved context below to test claims.")
    extra_block = ("\n- " + "\n- ".join(extras)) if extras else ""
    ctx_block = f"\n\n=== RETRIEVED / CITED CONTEXT ===\n{retrieval_context}" if retrieval_context else ""
    return (
        f"{base_sys}\n\n"
        f"===[EXPLORATION MODE: {mode}]===\n{frag}{extra_block}\n"
        f"===[CURRENT HOP: {hop.upper()}]==={ctx_block}"
    )

# ==========================================
# 4. TOKENIZER + TEXT HELPERS
# ==========================================

_TOK = None
_TOK_LOCK = threading.Lock()

def _tokenizer():
    """Qwen3 tokenizer from the local model dir (falls back to tiktoken)."""
    global _TOK
    if _TOK is None:
        with _TOK_LOCK:
            if _TOK is None:
                try:
                    from transformers import AutoTokenizer
                    _TOK = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
                except Exception as e:
                    print(f"[WARN] HF tokenizer unavailable ({e}); using tiktoken cl100k_base.")
                    import tiktoken
                    _TOK = tiktoken.get_encoding("cl100k_base")
    return _TOK

def truncate_text_to_tokens(text, max_tokens):
    if not text:
        return ""
    tok = _tokenizer()
    try:
        ids = tok.encode(text, add_special_tokens=False)
    except TypeError:            # tiktoken
        ids = tok.encode(text)
    if len(ids) <= max_tokens:
        return text
    return tok.decode(ids[:max_tokens]) + " ... [TRUNCATED]"

def clean_text_detailed(text):
    if pd.isna(text) or text is None:
        return ""
    text = str(text).replace("\n", " ")
    text = re.sub(r"\S+\s+et\s+al\.?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\d+", "", text)
    return re.sub(r"\s+", " ", text).strip()

def build_evidence_tagged(paper_text):
    """Tag sentences with [E#] IDs so agents can cite evidence IDs in strict mode."""
    chunks = re.split(r"(?<=[.!?])\s+", paper_text)
    tagged, n = [], 0
    for c in chunks:
        c = c.strip()
        if not c:
            continue
        n += 1
        tagged.append(f"[E{n}] {c}")
    return " ".join(tagged)

def extract_intro_and_abstract(cited_entry, top_k=8):
    """Parse the cited-papers column into a compact retrieval context (top_k papers)."""
    if cited_entry is None or (isinstance(cited_entry, float) and pd.isna(cited_entry)):
        return ""
    try:
        parsed = ast.literal_eval(cited_entry) if isinstance(cited_entry, str) else cited_entry
    except Exception:
        return ""
    if not isinstance(parsed, dict):
        return ""
    processed = []
    for idx, (pid, data) in enumerate(parsed.items(), 1):
        if idx > top_k:
            break
        if not isinstance(data, dict):
            continue
        intro = ""
        for sec in data.get("sections", []) or []:
            if "introduction" in str(sec.get("heading", "")).lower():
                intro = sec.get("text", "")
                break
        t_clean = clean_text_detailed(data.get("title", ""))
        a_clean = clean_text_detailed(data.get("abstractText") or data.get("abstract"))
        i_clean = clean_text_detailed(intro)
        if t_clean or a_clean or i_clean:
            processed.append(
                f"Paper{idx}_Title: {t_clean}\nPaper{idx}_Abstract: {a_clean}\n"
                f"Paper{idx}_Introduction: {i_clean}"
            )
    return "\n\n".join(processed)

# ==========================================
# 5. vLLM CALL HELPER
# ==========================================

_client = OpenAI(base_url=VLLM_BASE_URL, api_key=VLLM_API_KEY, timeout=REQUEST_TIMEOUT,
                 max_retries=0)

def _count_tokens(text):
    tok = _tokenizer()
    try:
        return len(tok.encode(text, add_special_tokens=False))
    except TypeError:
        return len(tok.encode(text))

def llm_call(system_prompt, user_message, sampling_config, max_tokens=1024,
             model=None, temperature_override=None):
    """One chat completion against the vLLM OpenAI server (Qwen3-4B).

    - `enable_thinking` is forced off by default (Qwen3 chat-template kwarg).
    - Prompt is shrunk if system+user would overflow the context window.
    - Retries with exponential backoff on transient server errors.
    """
    model = model or SERVED_MODEL_NAME

    # --- context safety: never let prompt + max_tokens exceed the window ---
    budget = MAX_MODEL_LEN - max_tokens - 256          # 256 = chat-template overhead
    n_sys, n_usr = _count_tokens(system_prompt), _count_tokens(user_message)
    if n_sys + n_usr > budget:
        # shrink the system prompt first (it carries the paper), then the user msg
        sys_budget = max(512, budget - n_usr)
        system_prompt = truncate_text_to_tokens(system_prompt, sys_budget)
        n_sys = _count_tokens(system_prompt)
        if n_sys + n_usr > budget:
            user_message = truncate_text_to_tokens(user_message, max(256, budget - n_sys))

    kwargs = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "temperature": (sampling_config["temperature"] if temperature_override is None
                        else temperature_override),
        "top_p": sampling_config.get("top_p", 1.0),
        "max_tokens": max_tokens,
        "seed": sampling_config.get("seed", 42),
        "extra_body": {
            "chat_template_kwargs": {"enable_thinking": ENABLE_THINKING},
            "repetition_penalty": 1.05,
        },
    }

    last_err = None
    for attempt in range(MAX_RETRIES):
        try:
            resp = _client.chat.completions.create(**kwargs)
            out = resp.choices[0].message.content or ""
            if not ENABLE_THINKING:
                out = re.sub(r"<think>.*?</think>", " ", out, flags=re.DOTALL | re.IGNORECASE)
            return out.strip()
        except Exception as e:
            last_err = e
            sleep = min(30, (2 ** attempt) + random.random())
            print(f"  [retry {attempt+1}/{MAX_RETRIES}] {type(e).__name__}: {e} — sleeping {sleep:.1f}s")
            time.sleep(sleep)
    print(f"  [ERROR] llm_call failed after {MAX_RETRIES} tries: {last_err}")
    return ""

# ==========================================
# 6. WORKER 3-HOP CHAIN (mode-aware)
# ==========================================

def run_worker_hops(worker_name, base_sys, specialty, mode, action,
                    rollout_config, retrieval_context=""):
    """SEARCH -> QUERY -> DRAFT for one worker. Returns (draft, hop_records)."""
    hop_records, hop_out = [], {}

    for hop in ("search", "query", "draft"):
        sys_prompt = build_agent_system(base_sys, mode, hop, action,
                                        retrieval_context if hop == "search" else "")
        if hop == "search":
            user_msg = (
                f"[Leader_Agent]: {worker_name}, analyze the paper and identify "
                f"limitations focused on {specialty}.\n\n" + HOP_USER_INSTRUCTIONS["search"]
            )
        elif hop == "query":
            prior = truncate_text_to_tokens(hop_out.get("search", ""), 3000)
            user_msg = HOP_USER_INSTRUCTIONS["query"].format(search_out=prior)
        else:
            prior = truncate_text_to_tokens(hop_out.get("query", ""), 3500)
            user_msg = HOP_USER_INSTRUCTIONS["draft"].format(query_out=prior)

        mt = 900 if hop != "draft" else 1400
        out = llm_call(sys_prompt, user_msg, rollout_config, max_tokens=mt, model=WORKER_MODEL)
        hop_out[hop] = out
        hop_records.append({
            "agent_role": "worker", "agent_name": worker_name,
            "turn_type": f"hop_{hop}", "mode": mode, "hop": hop,
            "input_messages": [
                {"role": "system", "content": sys_prompt},
                {"role": "user", "content": user_msg},
            ],
            "output": out,
        })

    draft = hop_out.get("draft", "").strip() or hop_out.get("query", "").strip()
    return draft, hop_records

def run_worker_full(worker_spec, worker_paper, mode, action, rollout_config,
                    retrieval_context, leader_sys, leader_cfg, paper_idx,
                    ground_truth, rc_meta, leader_meta):
    """3 hops + the mode's critique rounds for ONE worker. Thread-safe: returns
    (worker_name, final_output, samples) and touches no shared state."""
    worker_name, prompt_fn, specialty = worker_spec
    base_sys = prompt_fn(worker_paper)
    samples = []

    worker_draft, hop_records = run_worker_hops(
        worker_name, base_sys, specialty, mode, action,
        rollout_config, retrieval_context=retrieval_context,
    )
    for rec in hop_records:
        rec.update({"paper_idx": paper_idx, "rollout_id": rollout_config["rollout_id"],
                    "rollout_config": rc_meta, "ground_truth": ground_truth})
        samples.append(rec)

    worker_current = worker_draft

    for r in range(action.get("critique_rounds", 0)):
        fb_user = (
            f"Worker '{worker_name}' (specialty: {specialty}) submitted this list "
            f"(critique round {r+1}):\n\n{worker_current}\n\n"
            "Provide targeted feedback (MODE A) to improve specificity, evidence "
            "grounding, and coverage. End with the required instruction."
        )
        leader_fb = llm_call(leader_sys, fb_user, leader_cfg, max_tokens=700, model=LEADER_MODEL)
        samples.append({
            "paper_idx": paper_idx, "rollout_id": rollout_config["rollout_id"],
            "rollout_config": leader_meta,
            "agent_role": "leader", "agent_name": "Leader_Agent",
            "turn_type": "feedback_to_worker", "mode": mode,
            "critique_round": r + 1, "target_worker": worker_name,
            "input_messages": [
                {"role": "system", "content": leader_sys},
                {"role": "user", "content": fb_user},
            ],
            "output": leader_fb, "ground_truth": ground_truth,
        })

        rev_sys = build_agent_system(base_sys, mode, "draft", action)
        rev_user = (
            f"[Your previous answer]:\n{worker_current}\n\n"
            f"[Leader_Agent feedback]:\n{leader_fb}\n\n"
            "Return ONLY your revised bullet list."
        )
        worker_current = llm_call(rev_sys, rev_user, rollout_config, max_tokens=1400,
                                  model=WORKER_MODEL)
        samples.append({
            "paper_idx": paper_idx, "rollout_id": rollout_config["rollout_id"],
            "rollout_config": rc_meta,
            "agent_role": "worker", "agent_name": worker_name,
            "turn_type": "revised", "mode": mode, "critique_round": r + 1,
            "input_messages": [
                {"role": "system", "content": rev_sys},
                {"role": "user", "content": rev_user},
            ],
            "output": worker_current, "ground_truth": ground_truth,
        })

    return worker_name, worker_current, samples

# ==========================================
# 7. ONE ROLLOUT (mode-driven pipeline, NO rewards)
# ==========================================

def execute_single_rollout(paper_idx, paper_text, evidence_text, citation_text,
                           ground_truth, rollout_config):
    mode = rollout_config["mode"]
    action = MODE_ACTION_CONFIG[mode]

    worker_paper = evidence_text if action.get("cite_evidence_ids") else paper_text
    retrieval_context = ""
    if action.get("use_retrieval"):
        retrieval_context = truncate_text_to_tokens(
            citation_text, min(CITATION_TOKEN_LIMIT, action.get("retrieval_top_k", 8) * 500)
        )

    leader_sys = get_leader_system_prompt()
    master_sys = get_master_system_prompt()

    rc_meta = {k: rollout_config[k] for k in ("temperature", "top_p", "seed", "mode")}
    ridx = rollout_config["rollout_id"]
    leader_cfg = LEADER_CONFIGS[ridx % len(LEADER_CONFIGS)]
    master_cfg = MASTER_CONFIGS[ridx % len(MASTER_CONFIGS)]
    leader_meta = {**{k: leader_cfg[k] for k in ("temperature", "top_p", "seed")}, "mode": mode}
    master_meta = {**{k: master_cfg[k] for k in ("temperature", "top_p", "seed")}, "mode": mode}

    # ---------- WORKERS in parallel (vLLM batches the concurrent requests) ----------
    samples = []
    all_worker_final = {}
    with ThreadPoolExecutor(max_workers=max(1, N_WORKER_THREADS)) as ex:
        futures = [
            ex.submit(run_worker_full, wspec, worker_paper, mode, action, rollout_config,
                      retrieval_context, leader_sys, leader_cfg, paper_idx,
                      ground_truth, rc_meta, leader_meta)
            for wspec in WORKER_CONFIGS
        ]
        results = [f.result() for f in futures]

    # keep a deterministic order (worker registry order) regardless of finish order
    order = {w[0]: i for i, w in enumerate(WORKER_CONFIGS)}
    results.sort(key=lambda t: order[t[0]])
    for wname, wfinal, wsamples in results:
        all_worker_final[wname] = wfinal
        samples.extend(wsamples)

    # ---------- LEADER HANDOFF ----------
    leader_bundle_user = (
        "You have collected revised outputs from all 6 specialist workers. Produce the "
        "MODE B handoff to the Master Agent. Here are the 6 outputs:\n\n"
        + "\n\n".join([f"### {w}:\n{o}" for w, o in all_worker_final.items()])
    )
    leader_handoff = llm_call(leader_sys, leader_bundle_user, leader_cfg,
                              max_tokens=1800, model=LEADER_MODEL)
    samples.append({
        "paper_idx": paper_idx, "rollout_id": rollout_config["rollout_id"],
        "rollout_config": leader_meta,
        "agent_role": "leader", "agent_name": "Leader_Agent",
        "turn_type": "handoff_to_master", "mode": mode,
        "input_messages": [
            {"role": "system", "content": leader_sys},
            {"role": "user", "content": leader_bundle_user},
        ],
        "output": leader_handoff, "ground_truth": ground_truth,
    })

    # ---------- MASTER ----------
    master_sys_eff = master_sys
    if APPLY_MASTER_TOT:
        master_sys_eff = master_sys + (
            "\n\n[TREE-OF-THOUGHT + SELF-REPAIR] Internally explore a few distinct "
            "consolidation paths (different groupings / prioritizations), pick the "
            "strongest, then self-critique it once and repair any weak, redundant, or "
            "poorly-grounded points before returning the FINAL list only."
        )
    master_output = llm_call(master_sys_eff, leader_handoff, master_cfg,
                             max_tokens=1800, model=MASTER_MODEL)
    samples.append({
        "paper_idx": paper_idx, "rollout_id": rollout_config["rollout_id"],
        "rollout_config": master_meta,
        "agent_role": "master", "agent_name": "Master_Agent",
        "turn_type": "synthesis", "mode": mode,
        "input_messages": [
            {"role": "system", "content": master_sys_eff},
            {"role": "user", "content": leader_handoff},
        ],
        "output": master_output, "ground_truth": ground_truth,
    })

    return {
        "mode": mode,
        "samples": samples,
        "final_master_output": master_output,
        "worker_final": all_worker_final,
    }

# ==========================================
# 8. SAVE / CONSOLIDATE
# ==========================================

def consolidate_and_save(all_paper_records):
    with open(OUTPUT_FULL_JSON, "w") as f:
        json.dump(all_paper_records, f, indent=2)

    worker, leader, master = [], [], []
    for paper in all_paper_records:
        for rollout in paper.get("rollouts", []):
            for s in rollout.get("samples", []):
                role = s.get("agent_role")
                if   role == "worker": worker.append(s)
                elif role == "leader": leader.append(s)
                elif role == "master": master.append(s)

    with open(OUTPUT_WORKER_JSON, "w") as f: json.dump(worker, f, indent=2)
    with open(OUTPUT_LEADER_JSON, "w") as f: json.dump(leader, f, indent=2)
    with open(OUTPUT_MASTER_JSON, "w") as f: json.dump(master, f, indent=2)

    print(f"  workers:{len(worker)} leader:{len(leader)} master:{len(master)}")

def wait_for_server(max_wait=1200):
    """Block until the vLLM server answers /models."""
    t0 = time.time()
    while time.time() - t0 < max_wait:
        try:
            models = [m.id for m in _client.models.list().data]
            print(f"vLLM ready. Served models: {models}")
            for name in {WORKER_MODEL, LEADER_MODEL, MASTER_MODEL}:
                if name not in models:
                    print(f"[WARN] '{name}' not in served models — requests will 404.")
            return True
        except Exception:
            time.sleep(10)
    raise RuntimeError(f"vLLM at {VLLM_BASE_URL} never became ready.")

# ==========================================
# 9. MAIN
# ==========================================

def run_pipeline():
    print("=" * 66)
    print("QWEN3-4B ROLLOUT GENERATION (vLLM)")
    print("=" * 66)
    print(f"model dir : {MODEL_PATH}")
    print(f"vllm url  : {VLLM_BASE_URL}")
    print(f"served    : worker={WORKER_MODEL} leader={LEADER_MODEL} master={MASTER_MODEL}")
    print(f"thinking  : {'ON' if ENABLE_THINKING else 'OFF'}")
    print(f"out dir   : {OUTPUT_DIR}")

    wait_for_server()

    print(f"Loading CSV: {INPUT_CSV}")
    df_full = pd.read_csv(INPUT_CSV)
    row_end = ROW_END if ROW_END is not None else len(df_full)
    df = df_full.iloc[ROW_START:row_end].copy().reset_index(drop=True)
    print(f"Processing the configured slice with {len(ROLLOUT_CONFIGS)} mode-rollouts per paper.")

    all_paper_records = []
    existing_checkpoints = set(os.listdir(CHECKPOINT_DIR))

    for local_i in tqdm(range(len(df)), desc="Papers"):
        global_i = ROW_START + local_i
        ckpt_name = f"paper_{global_i:05d}.json"
        ckpt_path = os.path.join(CHECKPOINT_DIR, ckpt_name)

        if ckpt_name in existing_checkpoints:
            try:
                with open(ckpt_path, "r") as f:
                    cached = json.load(f)
                has_real = any(len(r.get("samples", [])) > 0 for r in cached.get("rollouts", []))
                if has_real:
                    all_paper_records.append(cached)
                    continue
                print(f"[RETRY] paper {global_i}: checkpoint empty, re-running")
            except Exception:
                pass

        row = df.iloc[local_i]
        paper_text   = str(row.get(INPUT_COL, ""))
        ground_truth = str(row.get(GT_COL, ""))
        citation_raw = row.get(CITATION_COL, "") if CITATION_COL in df.columns else ""

        paper_text    = truncate_text_to_tokens(paper_text, PAPER_TOKEN_LIMIT)
        evidence_text = truncate_text_to_tokens(build_evidence_tagged(paper_text), PAPER_TOKEN_LIMIT)
        citation_text = truncate_text_to_tokens(
            extract_intro_and_abstract(citation_raw, top_k=8), CITATION_TOKEN_LIMIT)

        if len(paper_text) < 100:
            print(f"[SKIP] paper {global_i}: text too short")
            continue

        paper_record = {
            "paper_idx": int(global_i),
            "paper_text": paper_text,
            "citation_text": citation_text,
            "ground_truth": ground_truth,
            "rollouts": [],
        }

        for rc in ROLLOUT_CONFIGS:
            print(f"  -> paper {global_i} | rollout {rc['rollout_id']} | mode={rc['mode']} "
                  f"(T={rc['temperature']}, seed={rc['seed']})")
            t0 = time.time()
            try:
                result = execute_single_rollout(
                    global_i, paper_text, evidence_text, citation_text, ground_truth, rc
                )
                paper_record["rollouts"].append({
                    "rollout_id": rc["rollout_id"],
                    "rollout_config": rc,
                    "mode": result["mode"],
                    "samples": result["samples"],
                    "final_master_output": result["final_master_output"],
                    "worker_final": result["worker_final"],
                })
                print(f"     done in {time.time()-t0:.1f}s "
                      f"({len(result['samples'])} samples)")
            except Exception as e:
                print(f"  [ERROR] paper {global_i} rollout {rc['rollout_id']}: {e}")
                paper_record["rollouts"].append({
                    "rollout_id": rc["rollout_id"], "rollout_config": rc, "mode": rc["mode"],
                    "error": str(e), "samples": [], "final_master_output": "", "worker_final": {},
                })

        with open(ckpt_path, "w") as f:
            json.dump(paper_record, f, indent=2)
        all_paper_records.append(paper_record)

        if (local_i + 1) % 5 == 0:
            consolidate_and_save(all_paper_records)

    consolidate_and_save(all_paper_records)
    print(f"\nDone (rollouts only). Outputs in: {OUTPUT_DIR}")
    print("Next: python select_data_stepwise_process_reward.py --rollout_json "
          f"{OUTPUT_FULL_JSON}")

if __name__ == "__main__":
    run_pipeline()